### ISSUE TITLE
Flush in BufferedWriter doesn't get called during the file rotation

### ISSUE THREAD

**Issue by naumenkovadym** [vy/hrrs#206]
I think that there could be an issue here: https://github.com/vy/hrrs/blob/master/serializer-base64/src/main/java/com/vlkan/hrrs/serializer/file/HttpRequestRecordWriterRotatingFileTarget.java#L53

The file in RotatingFileOutputStream could be changed, so the stream will be flushed, closed, and re-opened. But BufferedWriter may have some buffered data up to 8Kb (DEFAULT_MAX_BUFFER_SIZE) and it won't be flushed. So a single log line can be split between different files.

**Comment by vy** [comment]
@naumenkovadym, you have a point, this is indeed problematic. I thought of extending the `callbacks` of the employed `RotationConfig` with an extra one that uses `onTrigger()` to flush the `BufferedWriter` . But this will not work, since both `RotatingFileOutputStream#flush()` and `RotatingFileOutputStream#unsafeRotate()` (which notifies the callbacks) are `synchronized`, and this will cause a deadlock. I cannot think of anything but the user explicitly using `ByteMatchingRotationPolicy` (newly introduced in `rotating-fos` version `0.10.0`) to rotate after every, say, 1000 newlines. We can update the HRRS documentation to state this. WDYT?

**Comment by naumenkovadym** [comment]
hi @vy 
Thanks for your answer. Yeah I think that should be fine

**Comment by vy** [comment]
Fixed in 8eff90ba7805f3737b3ae8b10b3572b2daddce1e.

@naumenkovadym, mind answering some questions, please?

* Do you use HRRS?
* If so, ...
  * for what purpose?
  * do you (dis)like it?
  * do you have any feedback?
* Do you want me to make a new release? (Actually there no functional changes, just dependency updates.)

**Comment by naumenkovadym** [comment]
thanks for the fix @vy 
I like the HRRS lib very much!

But unfortunately, my use case is very specific and I can't use any of the existing libs for several reasons. For example:
1) Specific requirements for log format, rotation policy, file format, etc.
2) Need to use a queue for request writers, something like this: https://github.com/pierredavidbelanger/logback-awslogs-appender/blob/master/src/main/java/ca/pjer/logback/AsyncWorker.java
3) Need to replay the requests at the same rate. For example, between 00:00 and 01:00 I had 10k requests in total, and between 01:00 and 02:00 - 50k. Load test should do the same using the same requests.
4) Etc..

I'm just checking all the existing solutions for now.

By the way, there could be another small issue for specific Java versions here: https://github.com/vy/hrrs/blob/master/serializer-base64/src/main/java/com/vlkan/hrrs/serializer/file/HttpRequestRecordReaderFileSource.java#L83 for GZ input files.

https://bugs.java.com/bugdatabase/view_bug;jsessionid=53ede10dc8803210b03577eac43?bug_id=6519463

Probably, it's better to change it to"
```
    public String read() {
        try {
            return reader.readLine();
        } catch (EOFException error) {
            return null;
        } catch (IOException error) {
            String message = String.format("failed reading line (file=%s)", file);
            throw new RuntimeException(message, error);
        }
    }
```

**Comment by vy** [comment]
Thanks, fixed the `EOFException` issue. (I will make a release, though I first need to fix the failing build. :face_exhaling:)

For what it's worth, I am one of the Log4j maintainers. If there is anything I can help from that angle, just let me know.
